# -*- coding: utf-8 -*-
"""
Created on Wed Dec 16 18:59:51 2015

@author: dbray
"""

def reformat_exp_data(in_file, out_file):
    """ reformats an expression table generated by R to a GSEA compatible expression dataset """
    
    # open the input file
    f = open(in_file, 'r')
    o = open(out_file, 'w')
    
    # read the first line (sample names)
    ## get rid of new line, any ", and replace spaces with tabs
    line = f.readline()
    line = line.replace('\u2029', '')
    line = line.replace('"', '')
    line = line.replace(' ', '\t')
    
    # add name and description
    line = 'NAME' + '\t' + 'DESCRIPTION' + '\t' + line
    o.write(line)
    
    # read the rest of the lines
    while True:
        
        # read a given line
        line = f.readline()
        if not line:
            break # break out of the file at the end
        line = line.replace('"', '')
        line = line.replace('\u2029', '')
        
        # add 'na' to the description column
        line_parts = line.split()
        line = '\t'.join(line_parts[1:])
        line = line_parts[0] + '\t' + 'na' + '\t' + line + '\n'
        
        # write line to the output file
        o.write(line)
    
    # close the files
    f.close()
    o.close()
    
    return 1
    
def main():
    
    # set a current directory
    curr_dir = "C:/Users/dbray/Google Drive/COPD_project/FormattedData/"
    
    # define the input file
    in_file = curr_dir + "pooledExpMat.txt"
    
    # define an output file
    out_file = curr_dir + "pooledExpMat_GSEA.txt"
    
    # pass the directory, files to the script
    reformat_exp_data(in_file, out_file)
    
    
if __name__ == "__main__":
    main()
